### PR TITLE
automatic year update in footer

### PR DESCRIPTION
**Pull request by ssaumyaa7**
The year 2021 is directly written, we have to change that next year, but the code that I added will automatically update the year to current year.

### CODE REVIEW

**Comment by ssaumyaa7** [comment]
@plazzy99 here are the changes

**Comment by plazzy99** [comment]
@tusharnankani @seema1711 please review

**Review by tusharnankani — APPROVED** [review]
LGTM 👍🏻

**Comment by seema1711** [comment]
Thank you @ssaumyaa7

**Pull request merged**
